title: KE4H Project
description: Our submission for the KE4H exam, comparing and contrasting local italian painters Francesco Paolo Michetti and Marcantonio Chiarini.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
