title: KE4H Project
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
